### PR TITLE
Migrate feature flags

### PR DESCRIPTION
**Pull request by TobyRet**
### Context

Currently feature flags on Find are controlled via environment variables. This means we need to redeploy whenever we want to toggle a flag.

Apply on the other hand has the means to toggle flags live in production with the need to redeploy.

We want to be able to store Feature Flag state in Redis and have the means to toggle feature flags via a basic-auth-protected UI

### Changes proposed in this pull request

- Migrate any current feature flags over to the new system
- Remove any old feature flag code / config

### Guidance to review
- Recommend reviewing per commit 
- Note that before merging, https://github.com/DFE-Digital/find-teacher-training/pull/1086 should be merged first and feature flag state should be set up correctly on on each environment

### Checklist

- [x] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

### CODE REVIEW

**Comment by davidgisbey** [comment]
if you toggle maintenance mode on you can't get back to the feature flag page. I think we need to add an exemption a skip before action to the controller

```
  skip_before_action :redirect_to_maintenance_page_if_flag_is_active

```

**Review by davidgisbey — APPROVED** [review]

**Comment by TobyRet** [comment]
> if you toggle maintenance mode on you can't get back to the feature flag page. I think we need to add an exemption a skip before action to the controller
> 
> ```
>   skip_before_action :redirect_to_maintenance_page_if_flag_is_active
> ```
Good spot @davidgisbey 

Have made the change - https://github.com/DFE-Digital/find-teacher-training/pull/1090/commits/293550109b58867c955843488da4e41658f3f62a

**Review by stevehook — COMMENTED** [review]
I had a look at the errors in `rails assets:precompile`. We don't need to initialise BigQuery for asset precompilation so I guess there is no need to run the initialiser though I can't see an easy way to 'switch it off'. There used to be an option in Rails like `config.assets.initialize_on_precompile = false` but that's been dropped in recent versions.

Is there are way to programmatically find out whether an initialiser is running for asset precompilation. If there is we could use that to just return immediately from `initializers/big_query.rb`. Failing that we could handle the exception in the same file, but that would mean that we could miss genuine Redis connectivity issues in future.

**Comment by TobyRet** [comment]
> I had a look at the errors in `rails assets:precompile`. We don't need to initialise BigQuery for asset precompilation so I guess there is no need to run the initialiser though I can't see an easy way to 'switch it off'. There used to be an option in Rails like `config.assets.initialize_on_precompile = false` but that's been dropped in recent versions.
> 
> Is there are way to programmatically find out whether an initialiser is running for asset precompilation. If there is we could use that to just return immediately from `initializers/big_query.rb`. Failing that we could handle the exception in the same file, but that would mean that we could miss genuine Redis connectivity issues in future.

@stevehook - looking at Apply it appears the big query initializer on checks for the existence of `BIG_QUERY_API_JSON_KEY` env var - the https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/config/initializers/bigquery.rb#L5

We could do something similar but then could get into a situation where the env var is not present but the big query feature flag is turned on ... But I'm assuming the app will raise an error if it makes and attempt to send events when big query has not been initialised?

**Comment by stevehook** [comment]
> > I had a look at the errors in `rails assets:precompile`. We don't need to initialise BigQuery for asset precompilation so I guess there is no need to run the initialiser though I can't see an easy way to 'switch it off'. There used to be an option in Rails like `config.assets.initialize_on_precompile = false` but that's been dropped in recent versions.
> > Is there are way to programmatically find out whether an initialiser is running for asset precompilation. If there is we could use that to just return immediately from `initializers/big_query.rb`. Failing that we could handle the exception in the same file, but that would mean that we could miss genuine Redis connectivity issues in future.
> 
> @stevehook - Thanks for checking this out. Looking at Apply it appears the big query initializer checks for the existence of `BIG_QUERY_API_JSON_KEY` env var - https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/config/initializers/bigquery.rb#L5
> 
> We could do something similar but then could get into a situation where the env var is not present but the big query feature flag is turned on ... But I'm assuming the app will raise an error if it makes and attempt to send events when big query has not been initialised?

If `BIG_QUERY_API_JSON_KEY` is missing when running the asset pipeline this is a better idea than anything I suggested.

**Pull request merged**
