### PR TITLE
Copy Rubocop config from Apply

### PR DESCRIPTION
**Pull request by duncanjbrown**
### Context

Since we reorganised the Apply Rubocop files into separate files, the `inherit_from` directive in this repo’s `.rubocop.yml`, which referenced the Apply `.rubocop.yml` on GitHub, was broken. This broke the build.

For technical reasons (see commit message) it's not possible to get GitHub and Rubocop to cooperate when we transitively include other Rubocop files from the Apply repo.

While we like parity, we don't like inheriting surprise work just because Apply happened to change something. And it's also a bit weird that we can't run Rubocop without a network connection. 

So change the approach: upgrade Rubocop so we're compatible with Apply, deliberately copy the whole config into this repo with a repeatable rake task, run it to copy the config, and fix all the new violations.

### Guidance to review

Check the rake task

### Link to Trello card

https://trello.com/c/GeHg9kpu/3524-fix-rubocop-in-find-to-unblock-builds

### Checklist

- [X] Rebased master
- [X] Cleaned commit history
- [X] Tested by running locally

### CODE REVIEW

**Review by TobyRet — COMMENTED** [review]
@duncanjbrown looks v good, but when I tried to run locally it appears to blow up when trying to call `ActiveSupport::TimeZone`

Does this happen for you as well?

```
NoMethodError: undefined method `today' for nil:NilClass
/Users/tobyretallick/Development/Clients/DFE/find-teacher-training/lib/tasks/rubocop.rake:15:in `block (2 levels) in <main>'
Tasks: TOP => rubocop:copy_config_from_apply
```

**Comment by duncanjbrown** [comment]
@TobyRet Maybe pull latest? I fixed this morning: https://github.com/DFE-Digital/find-teacher-training/pull/809/files#diff-beaa968b80c0f54c48ea13ecb2a7b3396b8a04dd4e81c3d911d83b2f363369a8R12

**Comment by TobyRet** [comment]
> @TobyRet Maybe pull latest? I fixed this morning: https://github.com/DFE-Digital/find-teacher-training/pull/809/files#diff-beaa968b80c0f54c48ea13ecb2a7b3396b8a04dd4e81c3d911d83b2f363369a8R12

That was it! Working now ta!

**Review by TobyRet — APPROVED** [review]
LGTM

**Pull request merged**
