### PR TITLE
Bump Node.Js 10 to 12.16.1

### PR DESCRIPTION
**Pull request by aliuk2012**
The reason for this bump is that Nodejs 10 is going in maintenance mode
from April 2020. To stay up to date on dependency, now might be a good
time to migrate to version 12.

https://nodejs.org/en/about/releases/

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product review

### CODE REVIEW

**Comment by defong** [comment]
What's actually holding this up?

Do we need to double check the docker file?

**Comment by TobyRet** [comment]
We will need a similar upgrade for Publish Teacher Training

**Comment by aliuk2012** [comment]
We need to check dockerfile and any where else in our pipeline where we depend on node

**Comment by aliuk2012** [comment]
@TobyRet I'm happy to create a similar pr for publish

**Pull request closed without merging**
